/**
 * Output-file portable-markdown check — `lint --check output`.
 *
 * Ports `scripts/verify-output.sh` as a pure TypeScript module.
 *
 * Every `.md` file directly under `<vault>/output/` (subdirectories are out of
 * scope — mirrors the bash script's `find -maxdepth 1 -type f -name '*.md'`)
 * MUST conform to the portable-markdown contract:
 *
 *   1. YAML frontmatter opening `---` on line 1.
 *   2. A closing `---` fence (frontmatter must be terminated).
 *   3. `generated_by: markdown` (unquoted or quoted) in frontmatter.
 *   4. `source_query:` field present in frontmatter.
 *   5. `generated_at: YYYY-MM-DD` field in frontmatter.
 *   6. `sources:` field present in frontmatter.
 *   7. No `[[wikilinks]]` in the body except on a trailing `*Generated by` line.
 *
 * Absent or empty `output/` is a clean state — the markdown skill may not have
 * run yet.
 *
 * Each violation produces one `Finding` of `{ severity: "warn", check:
 * "output-check" }`. The function returns findings sorted deterministically by
 * (file asc, message asc) so identical vaults always produce identical output.
 *
 * No `any` — all unknown is narrowed. No side effects beyond reading the
 * filesystem. No embeddings.
 */

import { join, relative } from "node:path";
import { readdirSync, statSync, existsSync } from "node:fs";
import { readFileSafe } from "./fs.ts";
import { splitFrontmatter } from "./frontmatter.ts";
import type { Finding } from "./report.ts";

// ── Constants ─────────────────────────────────────────────────────────────────

const CHECK = "output-check";

/**
 * `generated_by:` must equal `markdown`, with or without surrounding quotes.
 * Mirrors the bash case-match:
 *   `*$'\ngenerated_by: markdown'*` | `*$'\ngenerated_by: "markdown"'*`
 */
const GENERATED_BY_RE = /^generated_by:\s+(?:"markdown"|markdown)\s*$/m;

/** `source_query:` key present anywhere in the frontmatter block. */
const SOURCE_QUERY_RE = /^source_query:/m;

/** `generated_at: YYYY-MM-DD` — exactly the ISO-date pattern. */
const GENERATED_AT_RE = /^generated_at:\s+\d{4}-\d{2}-\d{2}\s*$/m;

/** `sources:` key present anywhere in the frontmatter block. */
const SOURCES_RE = /^sources:/m;

/** A `[[wikilink]]` appearing anywhere in text. */
const WIKILINK_RE = /\[\[[^\]]+\]\]/;

/** Attribution line prefix — the one body line allowed to carry wikilinks. */
const ATTRIBUTION_PREFIX = "*Generated by ";

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * List `.md` files directly in `dir` (maxdepth 1), sorted ascending.
 * Returns [] when `dir` does not exist.
 *
 * Matches `find "$OUTPUT_DIR" -maxdepth 1 -type f -name '*.md'` in the bash
 * twin — subdirectories and non-.md files are excluded.
 */
function listShallowMarkdown(dir: string): string[] {
  if (!existsSync(dir)) return [];
  const entries = readdirSync(dir).sort();
  const out: string[] = [];
  for (const name of entries) {
    if (!name.endsWith(".md")) continue;
    const full = join(dir, name);
    try {
      if (statSync(full).isFile()) out.push(full);
    } catch {
      // unreadable stat — skip silently (readFileSafe-style tolerance)
    }
  }
  return out;
}

/**
 * Audit a single output file for portable-markdown compliance.
 * Returns one `Finding` per violation found, each tagged with the file path.
 */
function checkFile(filePath: string, vaultRoot: string): Finding[] {
  const rel = relative(vaultRoot, filePath);
  const content = readFileSafe(filePath);
  if (content === null) {
    // Unreadable file — advisory warn; never throw.
    return [
      {
        severity: "warn",
        check: CHECK,
        message: `output-check: could not read file ${rel}`,
        file: rel,
      },
    ];
  }

  const findings: Finding[] = [];
  const lines = content.split("\n");

  // ── Check 1: opening fence ─────────────────────────────────────────────────
  if ((lines[0] ?? "").trim() !== "---") {
    findings.push({
      severity: "warn",
      check: CHECK,
      message: `output-check: missing opening --- in ${rel}`,
      file: rel,
    });
    // Without an opening fence the rest of the checks are meaningless; report
    // only this violation so the human has a clear starting fix.
    return findings;
  }

  // ── Check 2: closing fence ─────────────────────────────────────────────────
  let fmEndLine = -1;
  for (let i = 1; i < lines.length; i++) {
    if ((lines[i] ?? "").trim() === "---") {
      fmEndLine = i;
      break;
    }
  }
  if (fmEndLine === -1) {
    findings.push({
      severity: "warn",
      check: CHECK,
      message: `output-check: missing closing --- (unterminated frontmatter) in ${rel}`,
      file: rel,
    });
    // Can't isolate frontmatter — report only this violation.
    return findings;
  }

  // ── Isolate frontmatter and body ───────────────────────────────────────────
  // Use splitFrontmatter from frontmatter.ts (reuse, don't duplicate).
  const { frontmatter, body } = splitFrontmatter(content);
  // frontmatter should be non-null here since we've already verified the fences,
  // but guard for safety.
  const fm = frontmatter ?? "";

  // ── Check 3: generated_by: markdown ───────────────────────────────────────
  if (!GENERATED_BY_RE.test(fm)) {
    findings.push({
      severity: "warn",
      check: CHECK,
      message: `output-check: missing or wrong generated_by field (expected: markdown) in ${rel}`,
      file: rel,
    });
  }

  // ── Check 4: source_query ─────────────────────────────────────────────────
  if (!SOURCE_QUERY_RE.test(fm)) {
    findings.push({
      severity: "warn",
      check: CHECK,
      message: `output-check: missing source_query field in ${rel}`,
      file: rel,
    });
  }

  // ── Check 5: generated_at YYYY-MM-DD ─────────────────────────────────────
  if (!GENERATED_AT_RE.test(fm)) {
    findings.push({
      severity: "warn",
      check: CHECK,
      message: `output-check: missing or malformed generated_at field (expected YYYY-MM-DD) in ${rel}`,
      file: rel,
    });
  }

  // ── Check 6: sources ─────────────────────────────────────────────────────
  if (!SOURCES_RE.test(fm)) {
    findings.push({
      severity: "warn",
      check: CHECK,
      message: `output-check: missing sources field in ${rel}`,
      file: rel,
    });
  }

  // ── Check 7: no wikilinks in body (except *Generated by line) ────────────
  //
  // The body returned by splitFrontmatter starts immediately after the closing
  // `---` fence. We scan each line; any line containing [[...]] is a violation
  // unless it starts with `*Generated by ` (the skill's attribution convention).
  const bodyLines = body.split("\n");
  for (let i = 0; i < bodyLines.length; i++) {
    const line = bodyLines[i] ?? "";
    if (line.startsWith(ATTRIBUTION_PREFIX)) continue;
    if (WIKILINK_RE.test(line)) {
      const lineNum = fmEndLine + 1 + i + 1; // 1-based, relative to file start
      findings.push({
        severity: "warn",
        check: CHECK,
        message: `output-check: body wikilink at line ${lineNum} in ${rel} (portable-markdown must not contain [[wikilinks]] outside attribution)`,
        file: rel,
      });
    }
  }

  return findings;
}

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Check every `.md` file directly under `<vaultRoot>/output/` for
 * portable-markdown compliance and return one `Finding` per violation.
 *
 * @param vaultRoot Absolute path to the vault root (the directory that contains
 *   `output/`). Absent or empty `output/` is a clean state (returns []).
 * @returns Immutable array of findings sorted by (file asc, message asc).
 */
export function checkOutput(vaultRoot: string): readonly Finding[] {
  const outputDir = join(vaultRoot, "output");
  if (!existsSync(outputDir)) return Object.freeze([]);

  const files = listShallowMarkdown(outputDir);
  const all: Finding[] = [];

  for (const file of files) {
    all.push(...checkFile(file, vaultRoot));
  }

  // Deterministic sort: file asc, then message asc.
  all.sort((a, b) => {
    const fa = a.file ?? "";
    const fb = b.file ?? "";
    if (fa !== fb) return fa.localeCompare(fb);
    return a.message.localeCompare(b.message);
  });

  return Object.freeze(all);
}
