/**
 * TDD — failing first (RED) for lint --check output.
 *
 * Tests `checkOutput(vaultRoot: string): readonly Finding[]` from ./output-check.ts.
 *
 * Mirrors the portable-markdown contract enforced by scripts/verify-output.sh:
 * every file directly under <vault>/output/ MUST:
 *   1. open with a `---` frontmatter fence on line 1
 *   2. close that fence with a second `---`
 *   3. declare `generated_by: markdown` (quoted or unquoted) in frontmatter
 *   4. declare `source_query:` in frontmatter
 *   5. declare `generated_at: YYYY-MM-DD` in frontmatter
 *   6. declare `sources:` in frontmatter
 *   7. contain no `[[wikilinks]]` in the body except on a trailing `*Generated by` line
 *
 * Absent or empty output/ is clean. Subdirectories under output/ are not checked
 * (not part of the contract today — matches bash script `find -maxdepth 1`).
 */

import { test, expect, describe } from "bun:test";
import { makeVault } from "../test-helpers/sandbox/vault.ts";
import { checkOutput } from "./output-check.ts";

// ── Clean fixtures ─────────────────────────────────────────────────────────────

const VALID_OUTPUT_FILE = `---
generated_by: markdown
source_query: What is a wiki?
generated_at: 2024-01-15
sources:
  - "[[Source Page]]"
---

# What is a wiki?

A wiki is a collaborative website.

*Generated by [[markdown skill]]*
`;

const VALID_OUTPUT_FILE_QUOTED_GENERATED_BY = `---
generated_by: "markdown"
source_query: What is a wiki?
generated_at: 2024-03-01
sources:
  - "[[Source Page]]"
---

Body text.
`;

// ── Dirty fixtures (one violation each) ───────────────────────────────────────

const MISSING_OPENING_FENCE = `No frontmatter here.

Body text.
`;

const MISSING_CLOSING_FENCE = `---
generated_by: markdown
source_query: Something
generated_at: 2024-01-15
sources:
  - "[[Source]]"
Unterminated frontmatter — closing fence never appears.
`;

const WRONG_GENERATED_BY = `---
generated_by: something-else
source_query: Something
generated_at: 2024-01-15
sources:
  - "[[Source]]"
---

Body text.
`;

const MISSING_SOURCE_QUERY = `---
generated_by: markdown
generated_at: 2024-01-15
sources:
  - "[[Source]]"
---

Body text.
`;

const MISSING_GENERATED_AT = `---
generated_by: markdown
source_query: Something
sources:
  - "[[Source]]"
---

Body text.
`;

const MALFORMED_GENERATED_AT = `---
generated_by: markdown
source_query: Something
generated_at: not-a-date
sources:
  - "[[Source]]"
---

Body text.
`;

const MISSING_SOURCES = `---
generated_by: markdown
source_query: Something
generated_at: 2024-01-15
---

Body text.
`;

const BODY_WIKILINK_VIOLATION = `---
generated_by: markdown
source_query: Something
generated_at: 2024-01-15
sources:
  - "[[Source]]"
---

Body with [[Unexpected Wikilink]] here.
`;

const BODY_WIKILINK_ON_ATTRIBUTION_LINE = `---
generated_by: markdown
source_query: Something
generated_at: 2024-01-15
sources:
  - "[[Source]]"
---

Body without wikilinks.

*Generated by [[markdown skill]] on behalf of [[Author]]*
`;

// ── Tests ─────────────────────────────────────────────────────────────────────

describe("checkOutput", () => {
  // ── clean-state tests ────────────────────────────────────────────────────────

  test("absent output/ directory yields zero findings", () => {
    const sb = makeVault({ "CLAUDE.md": "---\nschema_version: 1\n---\n" });
    const findings = checkOutput(sb.vault);
    expect(findings).toHaveLength(0);
    sb.cleanup();
  });

  test("empty output/ directory yields zero findings", () => {
    const sb = makeVault({
      "CLAUDE.md": "---\nschema_version: 1\n---\n",
      "output/.gitkeep": "",
    });
    const findings = checkOutput(sb.vault);
    expect(findings).toHaveLength(0);
    sb.cleanup();
  });

  test("fully-conformant output file yields zero findings", () => {
    const sb = makeVault({
      "CLAUDE.md": "---\nschema_version: 1\n---\n",
      "output/wiki-article.md": VALID_OUTPUT_FILE,
    });
    const findings = checkOutput(sb.vault);
    expect(findings).toHaveLength(0);
    sb.cleanup();
  });

  test('quoted generated_by: "markdown" is accepted', () => {
    const sb = makeVault({
      "CLAUDE.md": "---\nschema_version: 1\n---\n",
      "output/article.md": VALID_OUTPUT_FILE_QUOTED_GENERATED_BY,
    });
    const findings = checkOutput(sb.vault);
    expect(findings).toHaveLength(0);
    sb.cleanup();
  });

  test("[[wikilinks]] on *Generated by attribution line are allowed", () => {
    const sb = makeVault({
      "CLAUDE.md": "---\nschema_version: 1\n---\n",
      "output/article.md": BODY_WIKILINK_ON_ATTRIBUTION_LINE,
    });
    const findings = checkOutput(sb.vault);
    expect(findings).toHaveLength(0);
    sb.cleanup();
  });

  // ── violation tests ──────────────────────────────────────────────────────────

  test("missing opening --- yields a finding", () => {
    const sb = makeVault({
      "CLAUDE.md": "---\nschema_version: 1\n---\n",
      "output/bad.md": MISSING_OPENING_FENCE,
    });
    const findings = checkOutput(sb.vault);
    expect(findings.length).toBeGreaterThanOrEqual(1);
    const f = findings.find((x) => x.message.includes("opening"));
    expect(f).toBeDefined();
    expect(f?.severity).toBe("warn");
    expect(f?.check).toBe("output-check");
    sb.cleanup();
  });

  test("unterminated frontmatter (missing closing ---) yields a finding", () => {
    const sb = makeVault({
      "CLAUDE.md": "---\nschema_version: 1\n---\n",
      "output/bad.md": MISSING_CLOSING_FENCE,
    });
    const findings = checkOutput(sb.vault);
    const f = findings.find((x) => x.message.includes("closing"));
    expect(f).toBeDefined();
    expect(f?.severity).toBe("warn");
    expect(f?.check).toBe("output-check");
    sb.cleanup();
  });

  test("wrong generated_by value yields a finding", () => {
    const sb = makeVault({
      "CLAUDE.md": "---\nschema_version: 1\n---\n",
      "output/bad.md": WRONG_GENERATED_BY,
    });
    const findings = checkOutput(sb.vault);
    const f = findings.find((x) => x.message.includes("generated_by"));
    expect(f).toBeDefined();
    expect(f?.severity).toBe("warn");
    expect(f?.check).toBe("output-check");
    sb.cleanup();
  });

  test("missing source_query field yields a finding", () => {
    const sb = makeVault({
      "CLAUDE.md": "---\nschema_version: 1\n---\n",
      "output/bad.md": MISSING_SOURCE_QUERY,
    });
    const findings = checkOutput(sb.vault);
    const f = findings.find((x) => x.message.includes("source_query"));
    expect(f).toBeDefined();
    expect(f?.severity).toBe("warn");
    expect(f?.check).toBe("output-check");
    sb.cleanup();
  });

  test("missing generated_at field yields a finding", () => {
    const sb = makeVault({
      "CLAUDE.md": "---\nschema_version: 1\n---\n",
      "output/bad.md": MISSING_GENERATED_AT,
    });
    const findings = checkOutput(sb.vault);
    const f = findings.find((x) => x.message.includes("generated_at"));
    expect(f).toBeDefined();
    expect(f?.severity).toBe("warn");
    expect(f?.check).toBe("output-check");
    sb.cleanup();
  });

  test("malformed generated_at (not YYYY-MM-DD) yields a finding", () => {
    const sb = makeVault({
      "CLAUDE.md": "---\nschema_version: 1\n---\n",
      "output/bad.md": MALFORMED_GENERATED_AT,
    });
    const findings = checkOutput(sb.vault);
    const f = findings.find((x) => x.message.includes("generated_at"));
    expect(f).toBeDefined();
    expect(f?.severity).toBe("warn");
    expect(f?.check).toBe("output-check");
    sb.cleanup();
  });

  test("missing sources field yields a finding", () => {
    const sb = makeVault({
      "CLAUDE.md": "---\nschema_version: 1\n---\n",
      "output/bad.md": MISSING_SOURCES,
    });
    const findings = checkOutput(sb.vault);
    const f = findings.find((x) => x.message.includes("sources"));
    expect(f).toBeDefined();
    expect(f?.severity).toBe("warn");
    expect(f?.check).toBe("output-check");
    sb.cleanup();
  });

  test("[[wikilink]] in body (non-attribution line) yields a finding", () => {
    const sb = makeVault({
      "CLAUDE.md": "---\nschema_version: 1\n---\n",
      "output/bad.md": BODY_WIKILINK_VIOLATION,
    });
    const findings = checkOutput(sb.vault);
    const f = findings.find((x) => x.message.includes("wikilink"));
    expect(f).toBeDefined();
    expect(f?.severity).toBe("warn");
    expect(f?.check).toBe("output-check");
    sb.cleanup();
  });

  // ── multi-file and edge-case tests ──────────────────────────────────────────

  test("two bad files yield findings for both", () => {
    const sb = makeVault({
      "CLAUDE.md": "---\nschema_version: 1\n---\n",
      "output/bad-one.md": MISSING_SOURCE_QUERY,
      "output/bad-two.md": MISSING_SOURCES,
    });
    const findings = checkOutput(sb.vault);
    expect(findings.length).toBeGreaterThanOrEqual(2);
    sb.cleanup();
  });

  test("one clean file and one bad file yield findings only for the bad file", () => {
    const sb = makeVault({
      "CLAUDE.md": "---\nschema_version: 1\n---\n",
      "output/good.md": VALID_OUTPUT_FILE,
      "output/bad.md": MISSING_SOURCES,
    });
    const findings = checkOutput(sb.vault);
    expect(findings.length).toBeGreaterThanOrEqual(1);
    // All findings reference the bad file
    for (const f of findings) {
      expect(f.file).toContain("bad.md");
    }
    sb.cleanup();
  });

  test("finding carries the file path", () => {
    const sb = makeVault({
      "CLAUDE.md": "---\nschema_version: 1\n---\n",
      "output/article.md": BODY_WIKILINK_VIOLATION,
    });
    const findings = checkOutput(sb.vault);
    expect(findings.length).toBeGreaterThanOrEqual(1);
    for (const f of findings) {
      expect(f.file).toBeDefined();
    }
    sb.cleanup();
  });

  test("output is deterministic: same vault yields same ordered findings", () => {
    const sb = makeVault({
      "CLAUDE.md": "---\nschema_version: 1\n---\n",
      "output/alpha.md": MISSING_SOURCE_QUERY,
      "output/beta.md": MISSING_SOURCES,
    });
    const run1 = checkOutput(sb.vault);
    const run2 = checkOutput(sb.vault);
    expect(JSON.stringify(run1)).toBe(JSON.stringify(run2));
    sb.cleanup();
  });

  test("subdirectories under output/ are not checked", () => {
    // Matches bash `find -maxdepth 1 -type f -name '*.md'`: subdirs are out of scope.
    const sb = makeVault({
      "CLAUDE.md": "---\nschema_version: 1\n---\n",
      "output/subdir/bad.md": MISSING_SOURCES,
    });
    const findings = checkOutput(sb.vault);
    expect(findings).toHaveLength(0);
    sb.cleanup();
  });

  test("multiple violations in one file all appear as separate findings", () => {
    // A file missing both source_query and sources should produce at least two findings.
    const multiViolation = `---
generated_by: markdown
generated_at: 2024-01-15
---

Body text.
`;
    const sb = makeVault({
      "CLAUDE.md": "---\nschema_version: 1\n---\n",
      "output/multi.md": multiViolation,
    });
    const findings = checkOutput(sb.vault);
    // At minimum: missing source_query + missing sources
    expect(findings.length).toBeGreaterThanOrEqual(2);
    sb.cleanup();
  });

  test("non-.md files in output/ are ignored", () => {
    const sb = makeVault({
      "CLAUDE.md": "---\nschema_version: 1\n---\n",
      "output/image.png": "binary-data",
      "output/data.json": '{"key":"value"}',
    });
    const findings = checkOutput(sb.vault);
    expect(findings).toHaveLength(0);
    sb.cleanup();
  });
});
