#!/usr/bin/env bats
# Tests for scripts/verify-output.sh
#
# Behavior under test:
#   - Empty or absent output/ exits 0.
#   - Files with the required frontmatter and a clean body exit 0.
#   - Missing frontmatter fields fail with an explanatory message.
#   - Body wikilinks (outside the trailing attribution line) fail.
#   - Trailing `*Generated by …[[link]]…` attribution line is allowed.

load '../test_helper/common'

setup() {
  _load_helpers
  setup_fixture_vault
}

teardown() {
  teardown_fixture_vault
}

# --- happy paths -------------------------------------------------------------

@test "Output verifier: it passes on the canonical fixture vault with no output" {
  run bash "$REPO_ROOT/scripts/verify-output.sh" "$FIXTURE_VAULT"
  assert_success
  assert_output_empty
}

@test "Output verifier: it passes and stays silent when output/ is absent" {
  rm -rf "$FIXTURE_VAULT/output"
  run bash "$REPO_ROOT/scripts/verify-output.sh" "$FIXTURE_VAULT"
  assert_success
  assert_output_empty
}

@test "Output verifier: it passes and stays silent when output/ is empty" {
  rm -f "$FIXTURE_VAULT/output"/*.md
  run bash "$REPO_ROOT/scripts/verify-output.sh" "$FIXTURE_VAULT"
  assert_success
  assert_output_empty
}

# --- failure paths -----------------------------------------------------------

@test "Output verifier: it fails with an explanatory message when generated_by is missing" {
  cat >"$FIXTURE_VAULT/output/missing-generated-by.md" <<'MD'
---
source_query: "what about X?"
generated_at: 2026-04-25
sources: []
---

# Body
plain markdown body.
MD

  run bash "$REPO_ROOT/scripts/verify-output.sh" "$FIXTURE_VAULT"
  assert_status 1
  assert_output_contains "missing or wrong generated_by field"
}

@test "Output verifier: it fails with an explanatory message when generated_at is malformed" {
  cat >"$FIXTURE_VAULT/output/bad-date.md" <<'MD'
---
generated_by: markdown
source_query: "what about X?"
generated_at: yesterday
sources: []
---

# Body
plain markdown body.
MD

  run bash "$REPO_ROOT/scripts/verify-output.sh" "$FIXTURE_VAULT"
  assert_status 1
  assert_output_contains "missing or malformed generated_at"
}

@test "Output verifier: it fails when the body contains a stray [[wikilink]] outside the attribution line" {
  cat >"$FIXTURE_VAULT/output/leaks-wikilink.md" <<'MD'
---
generated_by: markdown
source_query: "what about X?"
generated_at: 2026-04-25
sources:
  - "[[Page A]]"
---

# Body
This sentence has a stray [[Wikilink]] that should not be here.
MD

  run bash "$REPO_ROOT/scripts/verify-output.sh" "$FIXTURE_VAULT"
  assert_status 1
  assert_output_contains "body wikilink"
}

@test "Output verifier: it allows wikilinks in the trailing Generated-by attribution line" {
  cat >"$FIXTURE_VAULT/output/clean-with-attribution.md" <<'MD'
---
generated_by: markdown
source_query: "what about X?"
generated_at: 2026-04-25
sources:
  - "[[Page A]]"
---

# Body
Plain markdown body with [a regular link](../wiki/topic/page.md).

---
*Generated by `/claude-wiki-pages:markdown` on 2026-04-25. Sources: [[Page A]], [[Page B]].*
MD

  run bash "$REPO_ROOT/scripts/verify-output.sh" "$FIXTURE_VAULT"
  assert_success
}

@test "Output verifier: it fails with usage and exits 2 when invoked without a vault argument" {
  run bash "$REPO_ROOT/scripts/verify-output.sh"
  assert_status 2
  assert_output_contains "usage:"
}

@test "Output verifier: it fails and exits 2 when the vault root does not exist" {
  run bash "$REPO_ROOT/scripts/verify-output.sh" "/no/such/vault/$$"
  assert_status 2
  assert_output_contains "vault root not found"
}
